# Generated by Django 5.1 on 2024-10-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peer_club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=10)),
                ('club_president', models.CharField(max_length=10)),
                ('contact_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.TextField(max_length=50)),
                ('student_email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=10)),
                ('admin_email', models.EmailField(max_length=10)),
                ('admin_role', models.CharField(max_length=10)),
                ('accept_student', models.CharField(max_length=10)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.peer_club')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField(max_length=10)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.admin')),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.peer_club')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.student')),
            ],
        ),
    ]
