# Generated by Django 5.1 on 2024-10-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0002_student_comments_student_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=15)),
                ('event_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='accept_student',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='comments',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peer.event'),
        ),
        migrations.DeleteModel(
            name='peer_club',
        ),
    ]
