# Generated by Django 5.1 on 2024-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0003_event_remove_registration_club_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_password',
            new_name='password',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.TextField(default=None, max_length=10),
        ),
    ]
