# Generated by Django 5.1 on 2024-10-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0004_rename_admin_email_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='peer.student'),
        ),
    ]
