# Generated by Django 5.1 on 2024-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0005_event_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_course',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
