# Generated by Django 5.1 on 2024-10-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0006_student_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_description',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
