# Generated by Django 5.1 on 2024-10-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0007_remove_event_event_description_event_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student_id',
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('fill_id', models.AutoField(primary_key=True, serialize=False)),
                ('fill_name', models.CharField(max_length=10)),
                ('fill_phone', models.CharField(max_length=50)),
                ('fill_email', models.EmailField(max_length=50)),
                ('fill_course', models.CharField(max_length=10)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.event')),
            ],
        ),
    ]
